I'm sorry, but errors were detected in your script. Please correct the
errors listed below, and try again.


File "game/historia.rpy", line 13: Indentation mismatch.

Ren'Py Version: Ren'Py 8.3.2.24090902
Wed Nov  6 20:09:01 2024
